1. Ordinal encoding: 
2. One hot encoding: Creates Vector to convert categorical data into numbers(0,1).

In [26]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [27]:
df = sns.load_dataset('tips')

In [28]:
encoder_time = LabelEncoder()
encoded_data_time = encoder_time.fit_transform(df['time'])

In [29]:
encoder_day = LabelEncoder()
encoded_data_day = encoder_day.fit_transform(df['day'])

In [30]:
for category, number in zip(encoder_time.classes_, range(len(encoder_time.classes_))):
    print(f"{category} --------- {number}")

Dinner --------- 0
Lunch --------- 1

In [31]:
for category, number in zip(encoder_day.classes_, range(len(encoder_day.classes_))):
    print(f"{category} --------- {number}")

Fri --------- 0
Sat --------- 1
Sun --------- 2
Thur --------- 3

In [32]:
encoder_day.inverse_transform([0,1,2,3])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe= OneHotEncoder(sparse_output=False)
ohe_encoder = ohe.fit_transform(df[['sex','smoker']])

In [35]:
ohe= OneHotEncoder(sparse_output=False, drop='first')
ohe_encoder_dropped = ohe.fit_transform(df[['sex','smoker']])

In [36]:
df1 = pd.DataFrame(ohe_encoder_dropped, columns=ohe.get_feature_names_out(['sex','smoker']))

In [37]:
df2 = pd.concat([df, df1], axis=1)

In [38]:
df2.drop(['sex','smoker'], axis=1, inplace=True)

C:\Users\rbhad\AppData\Local\Temp\ipykernel_21152\708472710.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df2.drop(['sex','smoker'], axis=1, inplace=True)

In [39]:
df2

     total_bill   tip   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01   Sun  Dinner     2       0.0         0.0
1         10.34  1.66   Sun  Dinner     3       1.0         0.0
2         21.01  3.50   Sun  Dinner     3       1.0         0.0
3         23.68  3.31   Sun  Dinner     2       1.0         0.0
4         24.59  3.61   Sun  Dinner     4       0.0         0.0
..          ...   ...   ...     ...   ...       ...         ...
239       29.03  5.92   Sat  Dinner     3       1.0         0.0
240       27.18  2.00   Sat  Dinner     2       0.0         1.0
241       22.67  2.00   Sat  Dinner     2       1.0         1.0
242       17.82  1.75   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Thur  Dinner     2       0.0         0.0

[244 rows x 7 columns]

In [40]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [41]:
log = FunctionTransformer(np.log10)
log.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [42]:
log_2 = FunctionTransformer(np.log2)
log_2.fit_transform(df['tip'])

0      0.014355
1      0.731183
2      1.807355
3      1.726831
4      1.851999
         ...
239    2.565597
240    1.000000
241    1.000000
242    0.807355
243    1.584963
Name: tip, Length: 244, dtype: float64

In [43]:
from sklearn.preprocessing import PowerTransformer

In [44]:
#1. Box-Cox Transformation: Positive data only
arr = np.array([[1], [1], [3], [5], [10], [50]])
boxcox = PowerTransformer(method='box-cox')
arr_boxcox = boxcox.fit_transform(arr)
print("Original Data:\n", arr.ravel())
print("Transformed Data:\n", np.round(arr_boxcox.ravel(),3))
print("Lambda Parameter:\n", boxcox.lambdas_)

Original Data:
 [ 1  1  3  5 10 50]
Transformed Data:
 [-1.205 -1.205 -0.15   0.255  0.73   1.574]
Lambda Parameter:
 [-0.23784507]

In [45]:
#2. Yeo-Johnson Transformation: Works with positive and negative data

yeo_johnson = PowerTransformer(method='yeo-johnson')
arr_transformed = yeo_johnson.fit_transform(arr)
print("Original Data:\n", arr.ravel())
print("Transformed Data:\n", np.round(arr_transformed.ravel(), 3))
print("Lambda Parameter:\n", yeo_johnson.lambdas_)

Original Data:
 [ 1  1  3  5 10 50]
Transformed Data:
 [-1.178 -1.178 -0.219  0.222  0.75   1.602]
Lambda Parameter:
 [-0.43652916]

In [47]:
from sklearn.impute import SimpleImputer

In [51]:
#filling missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan', 'Fiona', 'George', 'Hannah'],
    
    # --- Categorical Columns (with nulls) ---
    'Department': ['IT', 'HR', np.nan, 'Marketing', 'IT', np.nan, 'Finance', 'HR'],
    'City': ['New York', np.nan, 'London', 'Paris', 'Tokyo', 'London', np.nan, 'Tokyo'],
    'Education': ['Bachelors', 'Masters', 'Bachelors', None, 'PhD', 'Masters', 'Bachelors', None],
    
    # --- Numerical Columns (with nulls) ---
    'Age': [25, np.nan, 30, 35, np.nan, 28, 42, 31],
    'Salary': [50000, 62000, np.nan, 58000, 95000, np.nan, 80000, 67000],
    'Experience_Years': [2, 5, 4, np.nan, 12, 3, np.nan, 6]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print("--- DataFrame ---")
print(df)

--- DataFrame ---
      Name Department      City  Education   Age   Salary  Experience_Years
0    Alice         IT  New York  Bachelors  25.0  50000.0               2.0
1      Bob         HR       NaN    Masters   NaN  62000.0               5.0
2  Charlie        NaN    London  Bachelors  30.0      NaN               4.0
3    Diana  Marketing     Paris        NaN  35.0  58000.0               NaN
4     Evan         IT     Tokyo        PhD   NaN  95000.0              12.0
5    Fiona        NaN    London    Masters  28.0      NaN               3.0
6   George    Finance       NaN  Bachelors  42.0  80000.0               NaN
7   Hannah         HR     Tokyo        NaN  31.0  67000.0               6.0

In [52]:
imputer = SimpleImputer(strategy='mean')
df['New_Salary'] = imputer.fit_transform(df[['Salary']]).flatten()

In [53]:
df

,Name,Department,City,Education,Age,Salary,Experience_Years,New_Salary
0,Alice,IT,New York,Bachelors,25.0,50000.0,2.0,50000.000000
1,Bob,HR,NaN,Masters,NaN,62000.0,5.0,62000.000000
2,Charlie,NaN,London,Bachelors,30.0,NaN,4.0,68666.666667
3,Diana,Marketing,Paris,NaN,35.0,58000.0,NaN,58000.000000
4,Evan,IT,Tokyo,PhD,NaN,95000.0,12.0,95000.000000
5,Fiona,NaN,London,Masters,28.0,NaN,3.0,68666.666667
6,George,Finance,NaN,Bachelors,42.0,80000.0,NaN,80000.000000
7,Hannah,HR,Tokyo,NaN,31.0,67000.0,6.0,67000.000000

In [54]:
imputer = SimpleImputer(strategy='median')
df['New_Experience_Years'] = imputer.fit_transform(df[['Experience_Years']]).flatten()

In [55]:
df

,Name,Department,City,Education,Age,Salary,Experience_Years,New_Salary,New_Experience_Years
0,Alice,IT,New York,Bachelors,25.0,50000.0,2.0,50000.000000,2.0
1,Bob,HR,NaN,Masters,NaN,62000.0,5.0,62000.000000,5.0
2,Charlie,NaN,London,Bachelors,30.0,NaN,4.0,68666.666667,4.0
3,Diana,Marketing,Paris,NaN,35.0,58000.0,NaN,58000.000000,4.5
4,Evan,IT,Tokyo,PhD,NaN,95000.0,12.0,95000.000000,12.0
5,Fiona,NaN,London,Masters,28.0,NaN,3.0,68666.666667,3.0
6,George,Finance,NaN,Bachelors,42.0,80000.0,NaN,80000.000000,4.5
7,Hannah,HR,Tokyo,NaN,31.0,67000.0,6.0,67000.000000,6.0

In [ ]:
imputer = SimpleImputer(strategy='most_frequent')
df['New_Department'] = imputer.fit_transform(df[['Department']]).flatten()

In [57]:
df

,Name,Department,City,Education,Age,Salary,Experience_Years,New_Salary,New_Experience_Years,New_Department
0,Alice,IT,New York,Bachelors,25.0,50000.0,2.0,50000.000000,2.0,IT
1,Bob,HR,NaN,Masters,NaN,62000.0,5.0,62000.000000,5.0,HR
2,Charlie,NaN,London,Bachelors,30.0,NaN,4.0,68666.666667,4.0,HR
3,Diana,Marketing,Paris,NaN,35.0,58000.0,NaN,58000.000000,4.5,Marketing
4,Evan,IT,Tokyo,PhD,NaN,95000.0,12.0,95000.000000,12.0,IT
5,Fiona,NaN,London,Masters,28.0,NaN,3.0,68666.666667,3.0,HR
6,George,Finance,NaN,Bachelors,42.0,80000.0,NaN,80000.000000,4.5,Finance
7,Hannah,HR,Tokyo,NaN,31.0,67000.0,6.0,67000.000000,6.0,HR

In [58]:
imputer = SimpleImputer(strategy='most_frequent')
df['City'] = imputer.fit_transform(df[['City']]).flatten()

In [59]:
df

,Name,Department,City,Education,Age,Salary,Experience_Years,New_Salary,New_Experience_Years,New_Department
0,Alice,IT,New York,Bachelors,25.0,50000.0,2.0,50000.000000,2.0,IT
1,Bob,HR,London,Masters,NaN,62000.0,5.0,62000.000000,5.0,HR
2,Charlie,NaN,London,Bachelors,30.0,NaN,4.0,68666.666667,4.0,HR
3,Diana,Marketing,Paris,NaN,35.0,58000.0,NaN,58000.000000,4.5,Marketing
4,Evan,IT,Tokyo,PhD,NaN,95000.0,12.0,95000.000000,12.0,IT
5,Fiona,NaN,London,Masters,28.0,NaN,3.0,68666.666667,3.0,HR
6,George,Finance,London,Bachelors,42.0,80000.0,NaN,80000.000000,4.5,Finance
7,Hannah,HR,Tokyo,NaN,31.0,67000.0,6.0,67000.000000,6.0,HR